# Generated by Django 2.2 on 2019-04-22 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0002_auto_20190422_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='reviewText',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
